// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtVkZ7pVUX3jVKXPcu5lvgGnRMq2YVnB4',
    appId: '1:1047780531904:web:a026d28d8b5b53ee07d725',
    messagingSenderId: '1047780531904',
    projectId: 'first-362a4',
    authDomain: 'first-362a4.firebaseapp.com',
    storageBucket: 'first-362a4.appspot.com',
    measurementId: 'G-QHCX3FWVLG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDspFnwwsKffivEWeOAsBHS57XcsgQpmd0',
    appId: '1:1047780531904:android:d986cde75ad1d8ac07d725',
    messagingSenderId: '1047780531904',
    projectId: 'first-362a4',
    storageBucket: 'first-362a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR4jmZrV024GdoCz7EVz4WeVn0Djucqh4',
    appId: '1:1047780531904:ios:c7560b7713299cad07d725',
    messagingSenderId: '1047780531904',
    projectId: 'first-362a4',
    storageBucket: 'first-362a4.appspot.com',
    iosClientId: '1047780531904-9kqsrqute2p37jvom054f6pa4qf52rhd.apps.googleusercontent.com',
    iosBundleId: 'com.example.practice',
  );
}
